services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - 8080:80
    volumes:
      - ./laravel-tienda:/var/www
    depends_on: []

  react:
    build:
      context: ./react-tienda
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - 3000:3000
    volumes:
      - ./react-tienda:/app
    command: npm run dev
